### ISSUE TITLE
ハードコードされたデータをなくす

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/faclig#14]
オフセット等をフォーマットに出す

**Comment by Cj-bc** [comment]
今必要なもの:

- 各パーツのオフセット

**Comment by Cj-bc** [comment]
こんなかんじ？

```yaml
name: <model name>
author: Cj.BC_SD a.k.a Cj-bc
parts:
  contour:
    path: "contour.yaml"
    offset: [0, 0]
  leftEye:
    path: "leftEye.yaml"
    offset: [29, 15]
  rightEye:
    path: "rightEye.yaml"
    offset: [13, 15]
  nose:
    path: "nose.yaml"
    offset: [25, 20]
  mouth:
    path: "mouth.yaml"
    offset: [22, 24]
  hair:
    path: "hair.yaml"
    offset: [5, 0]
  backHair:
    path: "backHair.yaml"
    offset: [4, 0]
```
